#!/usr/bin/env bash

set -xeuo pipefail

SEDOPT="-i"
[[ "$OSTYPE" =~ darwin ]] && SEDOPT="-i ''"

DOC="https://www.microsoft.com/en-us/download/confirmation.aspx?id=56519"
DOCPAGE=$(mktemp)
curl -sSL -o "$DOCPAGE" "$DOC"
PUBLICJSONPAGE=$(grep ServiceTags.*\.json "$DOCPAGE" | \
  sed 's,.*"url":"\([^\"]*\)"\,"s.*,\1,')

JQREGIONFILTER=$(sed 's,\(.*\),.id == "\1",g' REGIONS | \
  awk '{print}' ORS=" or " | \
  sed 's, or $,,')
  PUBLICJSON=$(mktemp)
curl -sSLN -o "$PUBLICJSON" "$PUBLICJSONPAGE"
jq -r --arg REGIONS "$JQREGIONFILTER" '.values[] | select($REGIONS) | .properties.addressPrefixes[]' "$PUBLICJSON"
