#!/usr/bin/env bash

set -euo pipefail

XPATHOPT=""
[[ "$OSTYPE" =~ darwin ]] || XPATHOPT="-e"

DOC="https://www.microsoft.com/en-us/download/confirmation.aspx?id=56519"
DOCPAGE=$(mktemp)
curl -sSL -o "$DOCPAGE" "$DOC"
PUBLICJSONPAGE=$(xpath $XPATHOPT '//a[@data-bi-id="downloadretry"]/@href' "$DOCPAGE" 2>/dev/null | \
  cut -d'"' -f 2)

JQREGIONFILTER=$(sed 's,\(.*\),.id == "\1",g' REGIONS | \
  awk '{print}' ORS=" or " | \
  sed 's, or $,,')
  PUBLICJSON=$(mktemp)
curl -sSLN -o "$PUBLICJSON" "$PUBLICJSONPAGE"
jq -r --arg REGIONS "$JQREGIONFILTER" '.values[] | select($REGIONS) | .properties.addressPrefixes[]' "$PUBLICJSON"
